//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by wls.rc
//
#define IDB_SYM0                        105
#define IDB_SYM1                        106
#define IDB_SYM2                        107
#define IDB_SYM3                        108
#define IDB_SYM4                        109
#define IDB_SYM5                        110
#define IDB_SYM6                        111
#define IDB_SYM7                        112
#define IDB_SYM8                        113
#define IDB_SYM9                        114
#define IDB_TRANS0                      116
#define IDC_CURSOR1                     117
#define IDB_TRANS1                      118
#define IDB_TRANS2                      119
#define IDB_TRANS3                      120
#define IDB_TRANS4                      121
#define IDB_TRANS5                      122
#define IDB_TRANS6                      123
#define IDB_TRANS7                      124
#define IDC_SYM0                        1000
#define IDC_SYM1                        1001
#define IDC_SYM2                        1002
#define IDC_SYM3                        1003
#define IDC_SYM4                        1004
#define IDC_SYM5                        1005
#define IDC_SYM6                        1006
#define IDC_SYM7                        1007
#define IDC_SYM8                        1008
#define IDC_SYM9                        1009
#define IDC_COLUMNS                     1015
#define IDC_TRANS0                      1016
#define IDC_TRANSX                      1017
#define IDC_TRANSY                      1018
#define IDC_TRANS1                      1019
#define IDC_TRANS2                      1020
#define IDC_TRANS3                      1021
#define IDC_TRANS4                      1022
#define IDC_TRANS5                      1023
#define IDC_TRANS6                      1024
#define IDC_TRANS7                      1025
#define IDC_PERIOD1                     1029
#define IDC_PERIODTEXT                  1030
#define IDC_EDIT2                       1033
#define IDC_USEROW                      1033
#define IDC_RULESTRING                  1034
#define IDC_DUMPFILE                    1035
#define IDC_OUTPUTFILE                  1036
#define IDC_EDIT1                       1038
#define IDC_USECOL                      1038
#define IDC_ALLOBJECTS                  1039
#define IDC_PARENT                      1040
#define IDC_CONWAY                      1041
#define IDC_CHECK5                      1042
#define IDC_STOPONFOUND                 1042
#define IDC_COMBINE                     1042
#define IDC_OUTPUTFILEYN                1043
#define IDC_EDIT6                       1044
#define IDC_MAXCOUNT                    1044
#define IDC_STOPONSTEP                  1044
#define IDC_OUTPUTALLGEN                1045
#define IDC_EDIT7                       1047
#define IDC_COLCELLS                    1047
#define IDC_EDIT8                       1049
#define IDC_COLWIDTH                    1049
#define IDC_EDIT9                       1051
#define IDC_NEARCOLS                    1051
#define IDC_FOLLOW                      1052
#define IDC_FOLLOWGENS                  1053
#define IDC_SMART                       1054
#define IDC_DUMPFREQ                    1055
#define IDC_SMARTWINDOW                 1055
#define IDC_SMARTTHRESHOLD              1056
#define IDC_VIEWFREQ                    1057
#define IDC_SMARTON                     1057
#define IDC_DIAGSORT                    1058
#define IDC_ORDERWIDE                   1059
#define IDC_ORDERGENS                   1060
#define IDC_ORDERMIDDLE                 1061
#define IDC_OUTPUTCOLS                  1062
#define IDC_SMARTWINDOWSTAT             1063
#define IDC_SMARTTHRESHOLDSTAT          1064
#define IDC_CHECK1                      1065
#define IDC_FASTSYM                     1065
#define IDC_RADIO1                      1066
#define IDC_TAB1                        1067
#define IDC_KNIGHTSORT                  1074
#define IDC_ABOUT                       40001
#define IDC_EXIT                        40002
#define IDC_SYMMETRY                    40003
#define IDC_TRANSLATE                   40004
#define IDC_PERIOD                      40006
#define IDC_SEARCHSETTINGS              40007
#define IDC_ROWS                        40008
#define IDC_OUTPUTSETTINGS              40009
#define IDC_PREFERENCES                 40010
#define IDC_OPENSTATE                   40013
#define IDC_SAVEGAME                    40014
#define IDC_SEARCHSTART                 40015
#define IDC_SEARCHPAUSE                 40016
#define IDC_SEARCHRESET                 40017
#define IDC_SEARCHRESUME                40018
#define IDC_SEARCHBACKUP                40019
#define IDC_SAVEPATTERN                 40020
#define IDC_CLEAR                       40022
#define IDC_CLEARGEN                    40023
#define IDC_NEXTGEN                     40024
#define IDC_PREVGEN                     40025
#define IDC_EDITCOPY                    40026
#define IDC_TEST                        40027
#define IDC_SEARCHBACKUP2               40028
#define IDC_COPYRESULT                  40029
#define IDC_SHIFTGUP                    40032
#define IDC_SHIFTGDOWN                  40033
#define IDCSHIFTGLEFT                   40034
#define IDC_SHIFTGRIGHT                 40035
#define IDC_SHIFTGLEFT                  40036
#define IDC_SHIFTAUP                    40037
#define IDC_SHIFTADOWN                  40038
#define IDC_SHIFTALEFT                  40039
#define IDC_SHIFTARIGHT                 40040
#define IDC_SHIFTAPAST                  40041
#define IDC_SHIFTAFUTURE                40042
#define IDC_SEARCHPREPARE               40043
#define IDC_COPYCOMBINATION             40044
#define IDC_CLEARCOMBINATION            40047
#define ID_TRANS_GEN                    40055
#define ID_TRANS_ALL                    40056
#define ID_FLIP_GEN_H                   40057
#define ID_FLIP_GEN_V                   40058
#define ID_FLIP_ALL_H                   40059
#define ID_FLIP_ALL_V                   40060
#define ID_HIDESEL                      40061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40062
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
